### ISSUE TITLE
Enable per environment

### ISSUE THREAD

**Issue by L0laapk3** [miku3920/vscode-render-special-chars#1]
Hi there,

Very nice extension, I have been using it for quite a long time!

I was wondering if it would be possible to add some granularity to enabling the extension. Specifically, I would like to keep the extension active in the editor view, but disable it in the terminal view as it is mostly just annoying there.

![image](https://github.com/miku3920/vscode-render-special-chars/assets/6313423/c4249924-3947-4de8-a61c-ddd5d8f3c987)

**Comment by miku3920** [comment]
Thank you for your feedback and for using the extension for such a long time!

I apologize for the inconvenience caused. I will work on resolving this issue as soon as possible.

**Comment by L0laapk3** [comment]
No need to apologise, I don't pay you after all :P thank you for your work!

**Comment by miku3920** [comment]
I have addressed this issue and added a new option excludedSchemes. You can now customize which URIs you want to exclude!

**Comment by L0laapk3** [comment]
Thanks!
